site_name: "Grupo A ✈️"

theme:
  name: material
  features:
    - navigation.tabs

extra_css:
  - assets/custom.css  # Aplica o CSS personalizado

nav:
  - Home: index.md
  - A1 - 18/03/2025: atv1.md
  - A2 - 25/03/2025: atv2.md
  - A3 - 29/04/2025: atv3.md
  - A4 - 29/04/2025: atv4.md