site_name: "Grupo A ✈️"

theme:
  name: material
  features:
    - navigation.tabs

extra_css:
  - assets/custom.css  # Aplica o CSS personalizado
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.min.css

nav:
  - Home: index.md
  - A1 - 18/03/2025: atv1.md
  - A2 - 25/03/2025: atv2.md
  - A4 - 29/04/2025: atv4.md