site_name: "Projeto Teste MkDocs"

theme:
  name: material
  features:
    - navigation.tabs

extra_css:
  - assets/custom.css  # Aplica o CSS personalizado

nav:
  - Home: index.md
  - A1 - 18/03/2025: atv1.md