site_name: "Projeto Teste MkDocs"

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    primary: "#7CFC00"  # Barra de menus verde-limão
    accent: "#FFFFFF"   # Botões brancos

nav:
  - Home: index.md
